version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: umi_user
      POSTGRES_PASSWORD: umi_password
      POSTGRES_DB: umi_tasks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: